version: '3'
services:
  sal34_bot:
    image: ghcr.io/ileonidze/sal34_bot:latest
    container_name: sal34_bot
    restart: unless-stopped
    volumes:
      - ./buildings:/opt/bot/buildings
      - ./configs:/opt/bot/configs
      - ./data:/opt/bot/data
      - ./stats:/opt/bot/stats
      - ./users:/opt/bot/users
